title: The AI Prodigy # your name (or website title) here
logo: "/images/Avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! I am a dedicated Data Scientist with a strong background in the FinTech industry. My journey in the world of data is driven by a deep passion for Data Product Management and crafting innovative solutions. With a focus on excellence, I excel in translating intricate business challenges into actionable insights through the power of statistical analysis, machine learning, and data visualization.
  <br><br>
  <a href="https://www.linkedin.com/in/mapenzi-supaki/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-405123311-0 # your Google Analytics tracking ID here
